/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JhPdfViewer {
        /**
          * Page forward {MouseEvent} e
         */
        "pageNext": (e: MouseEvent) => Promise<void>;
        /**
          * Page backward e
         */
        "pagePrev": (e: MouseEvent) => Promise<void>;
        /**
          * Rotate the PDF in degrees {number}
         */
        "rotation": 0 | 90 | 180 | 270 | 360;
        /**
          * Src of the PDF to load and render {number}
         */
        "src": string;
    }
}
declare global {
    interface HTMLJhPdfViewerElement extends Components.JhPdfViewer, HTMLStencilElement {
    }
    var HTMLJhPdfViewerElement: {
        prototype: HTMLJhPdfViewerElement;
        new (): HTMLJhPdfViewerElement;
    };
    interface HTMLElementTagNameMap {
        "jh-pdf-viewer": HTMLJhPdfViewerElement;
    }
}
declare namespace LocalJSX {
    interface JhPdfViewer {
        "onPageChange"?: (event: CustomEvent<number>) => void;
        "onPageRendered"?: (event: CustomEvent<number>) => void;
        /**
          * Rotate the PDF in degrees {number}
         */
        "rotation"?: 0 | 90 | 180 | 270 | 360;
        /**
          * Src of the PDF to load and render {number}
         */
        "src"?: string;
    }
    interface IntrinsicElements {
        "jh-pdf-viewer": JhPdfViewer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jh-pdf-viewer": LocalJSX.JhPdfViewer & JSXBase.HTMLAttributes<HTMLJhPdfViewerElement>;
        }
    }
}
