/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  StencilPdfJs as JhPdfViewer
} from './components/jh-pdf-viewer/jh-pdf-viewer';

declare global {
  interface HTMLJhPdfViewerElement extends JhPdfViewer, HTMLStencilElement {
  }
  var HTMLJhPdfViewerElement: {
    prototype: HTMLJhPdfViewerElement;
    new (): HTMLJhPdfViewerElement;
  };
  interface HTMLElementTagNameMap {
    "jh-pdf-viewer": HTMLJhPdfViewerElement;
  }
  interface ElementTagNameMap {
    "jh-pdf-viewer": HTMLJhPdfViewerElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "jh-pdf-viewer": JSXElements.JhPdfViewerAttributes;
    }
  }
  namespace JSXElements {
    export interface JhPdfViewerAttributes extends HTMLAttributes {
      rotation?: 0 | 90 | 180 | 270 | 360;
      src?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
