/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface JhPdfViewer {
    /**
    * Page forward {MouseEvent} e
    */
    'pageNext': (e: MouseEvent) => void;
    /**
    * Page backward e
    */
    'pagePrev': (e: MouseEvent) => void;
    /**
    * Rotate the PDF in degrees {number}
    */
    'rotation': 0 | 90 | 180 | 270 | 360;
    /**
    * Src of the PDF to load and render {number}
    */
    'src': string;
  }
  interface JhPdfViewerAttributes extends StencilHTMLAttributes {
    'onOnError'?: (event: CustomEvent<any>) => void;
    'onPageChange'?: (event: CustomEvent<number>) => void;
    'onPageRendered'?: (event: CustomEvent<number>) => void;
    /**
    * Rotate the PDF in degrees {number}
    */
    'rotation'?: 0 | 90 | 180 | 270 | 360;
    /**
    * Src of the PDF to load and render {number}
    */
    'src'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'JhPdfViewer': Components.JhPdfViewer;
  }

  interface StencilIntrinsicElements {
    'jh-pdf-viewer': Components.JhPdfViewerAttributes;
  }


  interface HTMLJhPdfViewerElement extends Components.JhPdfViewer, HTMLStencilElement {}
  var HTMLJhPdfViewerElement: {
    prototype: HTMLJhPdfViewerElement;
    new (): HTMLJhPdfViewerElement;
  };

  interface HTMLElementTagNameMap {
    'jh-pdf-viewer': HTMLJhPdfViewerElement
  }

  interface ElementTagNameMap {
    'jh-pdf-viewer': HTMLJhPdfViewerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
